version: '3'
services:
  mysql:
    container_name: scraping-db
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - scraping-db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - scraping_default

volumes:
  scraping-db_data:

networks:
  scraping_default:
    external: true
